# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/krishnan/vivado_ws/vga/vga.srcs/sources_1/ip/pacman_map_blockmem/pacman_map_blockmem.xci
# IP: The module: 'pacman_map_blockmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/krishnan/vivado_ws/vga/vga.srcs/sources_1/ip/pacman_map_blockmem/pacman_map_blockmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pacman_map_blockmem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/krishnan/vivado_ws/vga/vga.srcs/sources_1/ip/pacman_map_blockmem/pacman_map_blockmem.xci
# IP: The module: 'pacman_map_blockmem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/krishnan/vivado_ws/vga/vga.srcs/sources_1/ip/pacman_map_blockmem/pacman_map_blockmem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pacman_map_blockmem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
