# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/krishnan/vivado_ws/vga/vga.srcs/sources_1/ip/num_sprite/num_sprite.xci
# IP: The module: 'num_sprite' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/krishnan/vivado_ws/vga/vga.srcs/sources_1/ip/num_sprite/num_sprite_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'num_sprite'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/krishnan/vivado_ws/vga/vga.srcs/sources_1/ip/num_sprite/num_sprite.xci
# IP: The module: 'num_sprite' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/krishnan/vivado_ws/vga/vga.srcs/sources_1/ip/num_sprite/num_sprite_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'num_sprite'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
