#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Nov 25 21:40:32 +03 2023
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim vga_out_tb_behav -key {Behavioral:sim_1:Functional:vga_out_tb} -tclbatch vga_out_tb.tcl -view /home/krishnan/vivado_ws/vga/vga_out_tb_behav.wcfg -log simulate.log"
xsim vga_out_tb_behav -key {Behavioral:sim_1:Functional:vga_out_tb} -tclbatch vga_out_tb.tcl -view /home/krishnan/vivado_ws/vga/vga_out_tb_behav.wcfg -log simulate.log

