webtalk_init -webtalk_dir /home/krishnan/vivado_ws/vga/vga.sim/sim_1/behav/xsim/xsim.dir/vga_out_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Nov 25 18:15:59 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211887999_1777552194_210720986_228" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a96630ac-e35e-4daf-86bd-1c179e3fbc3a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5d9bd712847341a08a8c5cf3bf2a01eb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "75" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3000.693 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "18" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "775 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "61 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "807" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "30" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.24_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "348272_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1890632253 -regid "211887999_1777552194_210720986_228" -xml /home/krishnan/vivado_ws/vga/vga.sim/sim_1/behav/xsim/xsim.dir/vga_out_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/krishnan/vivado_ws/vga/vga.sim/sim_1/behav/xsim/xsim.dir/vga_out_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/krishnan/vivado_ws/vga/vga.sim/sim_1/behav/xsim/xsim.dir/vga_out_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
